export const musicas = [
  {
    id: '1',
    titulo: 'Blinding Lights',
    artista: 'The Weeknd',
    album: 'After Hours',
    duracao: '3:20',
    capa: '🎵',
    favorita: false,
  },
  {
    id: '2',
    titulo: 'Shape of You',
    artista: 'Ed Sheeran',
    album: '÷',
    duracao: '3:53',
    capa: '🎶',
    favorita: false,
  },
  {
    id: '3',
    titulo: 'Anti-Hero',
    artista: 'Taylor Swift',
    album: 'Midnights',
    duracao: '3:21',
    capa: '🎤',
    favorita: false,
  },
  {
    id: '4',
    titulo: 'Heat Waves',
    artista: 'Glass Animals',
    album: 'Dreamland',
    duracao: '4:00',
    capa: '🎸',
    favorita: false,
  },
  {
    id: '5',
    titulo: 'As It Was',
    artista: 'Harry Styles',
    album: 'Harry\'s House',
    duracao: '2:57',
    capa: '🎵',
    favorita: false,
  },
  {
    id: '6',
    titulo: 'Good as Hell',
    artista: 'Lizzo',
    album: 'Cuz I Love You',
    duracao: '3:32',
    capa: '🎶',
    favorita: false,
  },
  {
    id: '7',
    titulo: 'levitating',
    artista: 'Dua Lipa',
    album: 'Future Nostalgia',
    duracao: '3:23',
    capa: '🎤',
    favorita: false,
  },
  {
    id: '8',
    titulo: 'Demon Slayer',
    artista: 'Imagine Dragons',
    album: 'Mercury Act 2',
    duracao: '3:11',
    capa: '🎸',
    favorita: false,
  },
  {
    id: '9',
    titulo: 'Starboy',
    artista: 'The Weeknd ft. Daft Punk',
    album: 'Starboy',
    duracao: '3:50',
    capa: '🎵',
    favorita: false,
  },
  {
    id: '10',
    titulo: 'Someone You Loved',
    artista: 'Lewis Capaldi',
    album: 'Divinely Uninspired...',
    duracao: '3:02',
    capa: '🎶',
    favorita: false,
  },
];
