export const musicas = [
  {
    id: '1',
    titulo: 'Blinding Lights',
    artista: 'The Weeknd',
    album: 'After Hours',
    duracao: '3:20',
    capa: '🎵',
    genero: 'Pop Eletrônico',
    anoLancamento: 2019,
    favorita: false,
  },
  {
    id: '2',
    titulo: 'Shape of You',
    artista: 'Ed Sheeran',
    album: '÷',
    duracao: '3:53',
    capa: '🎶',
    genero: 'Pop',
    anoLancamento: 2017,
    favorita: false,
  },
  {
    id: '3',
    titulo: 'Anti-Hero',
    artista: 'Taylor Swift',
    album: 'Midnights',
    duracao: '3:21',
    capa: '🎤',
    genero: 'Pop',
    anoLancamento: 2022,
    favorita: false,
  },
  {
    id: '4',
    titulo: 'Heat Waves',
    artista: 'Glass Animals',
    album: 'Dreamland',
    duracao: '4:00',
    capa: '🎸',
    genero: 'Indie Pop',
    anoLancamento: 2020,
    favorita: false,
  },
  {
    id: '5',
    titulo: 'As It Was',
    artista: 'Harry Styles',
    album: 'Harry\'s House',
    duracao: '2:57',
    capa: '🎵',
    genero: 'Pop',
    anoLancamento: 2022,
    favorita: false,
  },
  {
    id: '6',
    titulo: 'Good as Hell',
    artista: 'Lizzo',
    album: 'Cuz I Love You',
    duracao: '3:32',
    capa: '🎶',
    genero: 'Hip-Hop/Rap',
    anoLancamento: 2019,
    favorita: false,
  },
  {
    id: '7',
    titulo: 'Levitating',
    artista: 'Dua Lipa',
    album: 'Future Nostalgia',
    duracao: '3:23',
    capa: '🎤',
    genero: 'Disco-Pop',
    anoLancamento: 2020,
    favorita: false,
  },
  {
    id: '8',
    titulo: 'Radioactive',
    artista: 'Imagine Dragons',
    album: 'Night Visions',
    duracao: '3:06',
    capa: '🎸',
    genero: 'Indie Rock',
    anoLancamento: 2012,
    favorita: false,
  },
  {
    id: '9',
    titulo: 'Starboy',
    artista: 'The Weeknd ft. Daft Punk',
    album: 'Starboy',
    duracao: '3:50',
    capa: '🎵',
    genero: 'Pop Eletrônico',
    anoLancamento: 2016,
    favorita: false,
  },
  {
    id: '10',
    titulo: 'Someone You Loved',
    artista: 'Lewis Capaldi',
    album: 'Divinely Uninspired...',
    duracao: '3:02',
    capa: '🎶',
    genero: 'Pop',
    anoLancamento: 2018,
    favorita: false,
  },
  {
    id: '11',
    titulo: 'Billie Jean',
    artista: 'Michael Jackson',
    album: 'Thriller',
    duracao: '4:54',
    capa: '🎤',
    genero: 'Pop',
    anoLancamento: 1982,
    favorita: false,
  },
  {
    id: '12',
    titulo: 'Bohemian Rhapsody',
    artista: 'Queen',
    album: 'A Night at the Opera',
    duracao: '5:55',
    capa: '🎸',
    genero: 'Rock',
    anoLancamento: 1975,
    favorita: false,
  },
  {
    id: '13',
    titulo: 'Hey Jude',
    artista: 'The Beatles',
    album: 'Hey Jude',
    duracao: '7:11',
    capa: '🎵',
    genero: 'Rock',
    anoLancamento: 1968,
    favorita: false,
  },
  {
    id: '14',
    titulo: 'Imagine',
    artista: 'John Lennon',
    album: 'Imagine',
    duracao: '3:03',
    capa: '🎶',
    genero: 'Pop',
    anoLancamento: 1971,
    favorita: false,
  },
  {
    id: '15',
    titulo: 'Hotel California',
    artista: 'Eagles',
    album: 'Hotel California',
    duracao: '6:30',
    capa: '🎤',
    genero: 'Rock',
    anoLancamento: 1976,
    favorita: false,
  },
];

export const categorias = [
  {
    id: 'cat-1',
    nome: '🔥 Tendências',
    cor: '#FF69B4',
    generos: ['Pop', 'Hip-Hop/Rap'],
  },
  {
    id: 'cat-2',
    nome: '🎸 Rock',
    cor: '#8B5FBF',
    generos: ['Rock', 'Indie Rock'],
  },
  {
    id: 'cat-3',
    nome: '✨ Pop',
    cor: '#FF6B9D',
    generos: ['Pop', 'Pop Eletrônico', 'Disco-Pop'],
  },
  {
    id: 'cat-4',
    nome: '📼 Clássicos',
    cor: '#C24B8A',
    generos: ['Rock'],
  },
];
